apiVersion: scheduler.kalypso.io/v1alpha1
kind: BaseRepo
metadata:
  name: main
spec:
  repo: https://github.com/temporg235/testgitops-control-plane
  branch: main
  path: .
  commit: d217ba7f1b83cc3a7986048fc72b229b150e263b
